### ISSUE TITLE
Parse chainId as hex-encoded values instead of as string

### ISSUE THREAD

**Issue by gmkung** [kleros/contract-insights-snap#12]
Currently Metamask passes the chainId to the snap as a string like this "eip155:64" but the chainId is actually hex encoded (so eip155:64 actually means chainId=100, which is Gnosis chain). The current code reads the second part directly as the chainId, so the proposal is to hex decode the value before reading it.

**Comment by greenlucid** [comment]
Will be fixed in https://github.com/kleros/contract-insights-snap/pull/26
